### PR TITLE
edit: updated LED matrix related codes and adjusted indentation

### PR DESCRIPTION
**Pull request by ken551**
Hello.

I tried your example code on micro:bit maqueen, and found that "library_example5_ble_controller" was not working on my environment.
This was because of the definition of `microbit` on L10.
In other examples the definition was as below:
```
Adafruit_Microbit microbit;
```
However, in the example the definition was like:
```
Adafruit_Microbit_Matrix microbit;
```
This differenced seemed to cause the compilation error.
So I fixed codes as follows:

```
//definition of "microbit"
Adafruit_Microbit microbit;

//led matrix related codes
microbit.matrix.begin();
```
and then now the example app works.

I also changed other example codes (excluding codes in "More" folder), for I thought it may be a bit confusing if they aren't.

And, I adjusted the indentation to improve the readability.

I confirmed that all the examples that I edited are compilable and work on my micro maqueen.

Sorry for my poor English, and I hope this will help your repository.

### CODE REVIEW

**Comment by kd8bxp** [comment]
Thanks for the changes, 
sometimes it's really hard to keep up with the changes in the upstream libraries,
I am getting compile errors with your changes.
Maybe related to which versions of the Adafruit Microbit library and Adafruit GFX library being used?
I think the GFX library is the one causing my issues - can you tell me which version of the libraries you are using.
Thanks again, look forward to updating and fixing the code.

**Comment by ken551** [comment]
Thank you for your quick response.

In my environment:
* Adafruit GFX library: `1.9.0`
* Adafruit microbit Library: `1.2.2`

and I got no compile error.

I think they are the latest version, for I installed them today.

**Comment by kd8bxp** [comment]
Hmmmm, ok I'll investigate on my side. (GFX library 1.5.0 I got no compile error, but with 1.9.0 I did) 
and 2 months ago when I added in the joypad control, there were no compile errors - today there are - something has changed - but now it's a question of what.....
I will work on investigating on my side of things.
Thanks again

**Comment by ken551** [comment]
I think only the example5 (bt control example ) had a problem
and the examples other than the example 5 work properly without my changes.

Note that most of the changes I submitted was a kind of refactoring.
(sorry for the confusing PR...)

**Comment by kd8bxp** [comment]
I got that,(example5) but something has changed, when I tried to compile the other sketches with no changes I got compile errors. It is just going to take me a bit to figure out what I did, and what has changed. 
I got that the changes you made were refactoring, still something between my system and your system is different - I am getting compile errors with all the sketches I've tried (both before and after the changes you made).
It has to be on my side now, so I'll continue to work and see what I can find. 
Thanks again.

**Comment by kd8bxp** [comment]
Ok, I think I found the issue on my side "Adafruit_BusIo" library was out of date - wow, so many libraries that depend on other libraries. 
So I think your changes are working, and it was me that had the issues. I'll merge and update the library.properties file, and get a new version pushed out.
Thanks again, have a great day.

**Pull request merged**
